### ISSUE TITLE
Кэширование нормальных форм работает некорректно

### ISSUE THREAD

**Issue by opennota** [kmike/pymorphy2#101]
``` python
# -*- coding: utf-8 -*-
from pymorphy2 import MorphAnalyzer, units

m = MorphAnalyzer(
  path='/usr/local/lib/python2.7/dist-packages/pymorphy2_dicts_ru/data/',
  units=[units.DictionaryAnalyzer()]
  )
for p in m.parse(u'залом'):
    print p.normal_form, p.tag
```

Среди нормальных форм должна быть форма "зал". Её нет:

```
залом NOUN,inan,masc sing,nomn
залом NOUN,inan,masc sing,accs
залом NOUN,inan,masc sing,ablt
залом NOUN,anim,masc sing,nomn
зало NOUN,inan,neut sing,ablt
```

Если закомментировать строку https://github.com/kmike/pymorphy2/blob/07b7c675810e5f3347bf3d459d9a5353813514f5/pymorphy2/units/by_lookup.py#L33 , получаем правильный результат:

```
залом NOUN,inan,masc sing,nomn
залом NOUN,inan,masc sing,accs
зал NOUN,inan,masc sing,ablt
залом NOUN,anim,masc sing,nomn
зало NOUN,inan,neut sing,ablt
```

(Обнаружено при тестировании [портированного на Go словарного анализатора](https://github.com/opennota/morph).)

**Comment by kmike** [comment]
Спасибо! Мне было бы сложно этот баг найти.

Кстати, нет желания добавить https://github.com/opennota/morph в https://github.com/kmike/pymorphy2/wiki?

**Comment by opennota** [comment]
@kmike Добавил.
