### ISSUE TITLE
Склонение названийдолжностей

### ISSUE THREAD

**Issue by ckcnik** [kmike/pymorphy2#102]
Мне нужно склонять должности в родительский падеж. Думал решить это склонением по отдельности каждого слова в названии должности. С первым примером все ок:
1) Главный бухгалтер - главного бухгалтера
Со вторым такой подход не работает:
2) менеджер по проектам - менеджера по проектов
То есть, есть должности, которые нужно склонять частично, а не полностью все слова. Еще один пример:
Главный директор по продажам - главного директора по продаж.
и т. д.

**Comment by bzaar** [comment]
Duplicate of #87.

**Comment by kmike** [comment]
В общем случае нужно разобрать фразу, построить дерево, и от там уже думать. Есть проект по склонению фраз, на эвристиках: https://github.com/summerisgone/pyphrasy - но я не знаю, в какой он стадии.
