### ISSUE TITLE
Проблема с получением лексем

### ISSUE THREAD

**Issue by AniMeIIIkA** [kmike/pymorphy2#111]
Когда пытаюсь получить лексемы слова: "технический", откуда-то добавляется буква "т".
![image](https://user-images.githubusercontent.com/13556484/47070040-1b4ea180-d1f9-11e8-98f7-1f3a6dd59572.png)

**Comment by buriy** [comment]
Это от сокращения, которое может расшифровываться как "технический".

**Comment by buriy** [comment]
Фильтруйте по тегам, там у сокращений был какой-то тег, кажется.

**Comment by AniMeIIIkA** [comment]
да, я разобрался, спасибо, фильтр по тегу Abbr
