### ISSUE TITLE
Some POS tags can't be feteched through MorphAnalyzer().parse().tag.POS

### ISSUE THREAD

**Issue by BLKSerene** [kmike/pymorphy2#118]
Hi, I'm using pymorphy2's morphological analyzer to do Russian and Ukrainian POS tagging. I've noticed that numeral are tagged as 'NUMB', but the tag listed in the doc of pymorphy2 and OpenCopora is 'NUMR'. So when I try to fetch the POS tag of numerals through MorphAnalyzer().parse().tag.POS, it returns `None`. Is this a typo? (I don't speak Russian or Ukrainian, so I'm using Google Translate while reading the doc though...)
And the same problem with punctuations (with POS tag "PNCT") and unknown words (with POS tag "UNKN"), is `None` the expected result? (Currently, I have to use `tag._POS` the get the correct POS tag instead of `tag.POS`)

**Comment by opennota** [comment]
`NUMR` is a numeral (one, two, three), `NUMB` is a number `1, 2, 3`.

**Comment by BLKSerene** [comment]
Thanks, I got it.
