### ISSUE TITLE
What is status of development?

### ISSUE THREAD

**Issue by kuraga** [kmike/pymorphy2#125]
@kmike , @opennota , всё плохо? Может хоть в теги и в PyPI версию новую отправим?

**Comment by opennota** [comment]
А я чё? Я ничё. Я так, мимо проходил.

**Comment by victorbocharov** [comment]
@kmike , мы (OpenCorpora) видим, что словарь в pymorpy2 давно не обновляется. Я несколькими способами пытался с вами связаться, чтобы обсудить это и предложить помощь, но не получил ответа.

Чтобы исправить ситуацию с обновлением, мы планируем сделать форк pymorphy2 и далее их поддерживать своими силами. Мы бы очень хотели перед этим (или, лучше, вместо этого) обсудить с вами эту ситуацию. Я прошу вас отреагировать здесь или почтой.

cc @grandsbor

**Comment by kuraga** [comment]
@victorbocharov , есть новости?

**Comment by victorbocharov** [comment]
@kuraga @grandsbor в группе в тг продублирована эта проблема и задан вопрос, не хочет ли кто-то присоединиться к её решению. Хотелось бы, чтобы в этом участвовали более опытные Python-разработчики. Если таковые найдутся.

**Comment by insolor** [comment]
@victorbocharov у меня есть опыт программирования на Python (в том числе небольшой вклад в pymorphy2), надеюсь смогу чем-то помочь проекту. Но все-таки хотелось бы дождаться ответ от @kmike. Я вижу что он активен на github, странно что не отвечает. Можно еще попробовать ему на почту написать (если этого еще не делали)

**Comment by kuraga** [comment]
Еще могу предположить, что сообщество OpenDataScience может помочь со связью (https://opendatascience.slack.com).

**Comment by victorbocharov** [comment]
@insolor спасибо. Мне тоже хотелось бы реакции от @kmike . На почту и в телеграм я ему писал в июле.

**Comment by kmike** [comment]
Привет! Я постараюсь релиз 0.9 на выходных сделать. В телеграме про словари обсудим.

**Comment by kuraga** [comment]
Коллеги, а о каком телеграмме идет речь?

**Comment by victorbocharov** [comment]
@kuraga это я сделал группу в тг, чтобы @kmike мог спросить всех активных участников OpenCorpora (это источник словаря) одновременно. Словарь меняется и там возможны сюрпризы.

**Comment by kuraga** [comment]
Здорово, 0.9.1! См. также: #133 .

**Comment by victorbocharov** [comment]
@kuraga , мне кажется, что конкретно этот тикет (#125) можно закрывать, т.к. ответ на основной вопрос получен.
