### ISSUE TITLE
Как правильно склонять фамилии по родам?

### ISSUE THREAD

**Issue by FFire** [kmike/pymorphy2#129]
Что то ни как не могу разобраться со склонением по родам.
Есть фамилия женского рода, их нужно поставить в мужской род, т.е. из "Петрова" получить "Петров" и тд. 
Подскажите как правильно сделать такое склонение?

**Comment by insolor** [comment]
Сначала просто разбираете слово как в документации по pymorphy2:
```python
>>> import pymorphy2
>>> morph = pymorphy2.MorphAnalyzer() 
>>> p = morph.parse('Петрова')                                                  
>>> print(*p, sep='\n')                                                         
Parse(word='петрова', tag=OpencorporaTag('NOUN,anim,masc,Sgtm,Surn sing,gent'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 36, 1),))
Parse(word='петрова', tag=OpencorporaTag('NOUN,anim,masc,Sgtm,Surn sing,accs'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 36, 3),))
Parse(word='петрова', tag=OpencorporaTag('NOUN,anim,femn,Sgtm,Surn sing,nomn'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 36, 6),))
Parse(word='петрова', tag=OpencorporaTag('ADJF masc,sing,gent'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 2346, 1),))
Parse(word='петрова', tag=OpencorporaTag('ADJF femn,sing,nomn'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 2346, 7),))
Parse(word='петрова', tag=OpencorporaTag('ADJF neut,sing,gent'), normal_form='петров', score=0.16666666666666666, methods_stack=((<DictionaryAnalyzer>, 'петрова', 2346, 15),))
```
Получается 6 разборов, 3 из них - как фамилии (Surn - surname), остальные как полное прилагательное (ADJF - adjective full). Брать первый разбор - не вариант, потому что все разборы с одинаковым "скором" (`score=0.16666666666666666`), вам легко может попасться разбор как прилагательного, и все может сломаться (для этой фамилии все равно, но для других фамилий может получиться вообще не прилагательное, а какое-нибудь наречие, и нормальная форма не будет совпадать с нормальной формой как фамилии).

Поэтому фильтруем (`filter`) только разборы как фамилии (`'Surn' in x.tag`), дальше уже берем первый попавшийся вариант разбора (`next`), и потом получаем нормальную форму:
```python
>>> next(filter(lambda x: 'Surn' in x.tag, p)).normal_form                                                                                                                                    
'петров'
```
Если например изначально была мужская фамилия, нужно наоборот поставить в женскую форму, то тут нужно применить метод `inflect` (склонение):
```python
>>> next(filter(lambda x: 'Surn' in x.tag, p)).inflect({'femn','nomn'}).word
'петрова'
```
femn - ж.р., nomn - именительный падеж.

Если фамилия какая-нибудь редкая, то может вообще не определиться как фамилия, тогда `filter` вернет пустой набор значений, и `next` выкинет исключение `StopIteration`.

**Comment by FFire** [comment]
Да, вроде получается. Спасибо.

Тогда может еще подскажите, насколько правильный у меня подход к определению пола по ФИО?

Сначала я пытаюсь определить пол отдельно для Фамилии Имени и Отчества и считаю их score. Мужской скор положительное число, женский - отрицательное.
Если скор равен нулю то беру проверяю пол первого попавшегося разбора, а скор делю на 2.

Потом складываю все скоры и по результату определяю пол. 
Вроде все корректно работает, но что то мне кажется как то сложновато работает. Может есть более простой подход?

```
def get_gender (input_name):

    def gender_to_num (input_gender, input_score):
        if input_gender == "masc" : return input_score
        if input_gender == "femn" : return (-1) * input_score
        return 0.0

    def geder_exactly (input_str, tag_str):
        p = morph.parse(input_str)
        try:
            lexem =  next(filter(lambda x: tag_str and 'nomn' in x.tag, p))
            return (gender_to_num(lexem.tag.gender, lexem.score))
        except:
            return 0.0

    def total_not_exactly (input_name):
        gender = 0.0
        p = morph.parse(input_name)[0]
        gender = gender_to_num (p.tag.gender, p.score)
        return gender


    FIO = input_name.strip().split(' ')

    if len (FIO)>0 :
        Surn = FIO[0]
        Surn_gender = geder_exactly (Surn, 'Surn' )
        if Surn_gender == 0 : Surn_gender  = total_not_exactly (Surn) *.5
        gender = Surn_gender

    if len (FIO)>1 :
        Name = FIO[1]
        Name_gender = geder_exactly (Name, 'Name')
        if Name_gender == 0 : Name_gender = total_not_exactly (Name) *.5
        gender += Name_gender

    if len (FIO)>2 :
        Patr = FIO[2]
        Patr_gender = geder_exactly (Patr, 'Patr')
        if Patr_gender == 0 : Patr_gender = total_not_exactly (Patr) *.5
        gender += Patr_gender
        
    print ('--', input_name)
    if gender > 0 : return "male"
    if gender < 0 : return "female"
    return "none"

print (get_gender('Змиренкова Ирина Петровна'))
```

**Comment by insolor** [comment]
1. Мое мнение - нет смысла учитывать скор (не только в этом случае, а вообще). Скор говорит только о том, какой вариант чаще встречается в текстах вообще, но для определения 

2. Для определения пола нужно учитывать все разборы (не только первый попавшийся через `next()` или `[0]`). Могут быть варианты разбора и как мужского, и как женского с одинаковым скором, вы возьмете первый, а правильным окажется второй. В этом случае лучше вернуть 0 в сумме.

По коду:
* `tag_str and 'nomn' in x.tag` работает не так как вы думаете.  
   Это будет эквивалентно выражению `tag_str and ('nomn' in x.tag)` - результат будет зависеть только от второй части, т.к. любая непустая строка в `tag_str` будет эквивалентна `True`.  
   Вхождение тегов нужно проверять так: `{tag_str, 'nomn'} in x.tag`
* Лучше не засовывать все функции в одну, так вы не сможете протестировать работу функций по отдельности
* Несколько if можно заменить на цикл

Мой вариант:

```python
import pymorphy2

morph = pymorphy2.MorphAnalyzer()


def gender_to_num (input_gender):
    if input_gender == "masc" : return 1
    if input_gender == "femn" : return -1
    return 0


def gender_nomn(input_str, tag_str):
    p = morph.parse(input_str)
    try:
        only_nominative = filter(lambda x: {tag_str, 'nomn'} in x.tag, p)
        gender = sum(map(lambda lexem: gender_to_num(lexem.tag.gender), only_nominative))
        return gender
    except:
        return 0


def gender_guess(input_name):
    p = morph.parse(input_name)
    gender = sum(map(lambda lexem: gender_to_num(lexem.tag.gender), p))
    return gender


def get_gender(input_name):
    print('--', input_name)
    
    FIO = input_name.strip().split(' ')

    tags = ['Surn', 'Name', 'Patr']
    gender = 0
    
    for part, tag in zip(FIO, tags):
        # zip возвращает пары значений из FIO и tags,
        # например ("Сиденко", "Surn"), ("Ирина", "Name"), ("Петровна", "Patr")
        # Пары будут возвращаться пока одна из последовательностей FIO или tags не закончится
        gender_of_part = gender_nomn(part, tag)
        if gender_of_part == 0:
            gender_of_part = gender_guess(part) * .5
        print(gender_of_part)
        gender += gender_of_part
    
    print('gender:', gender)
    if gender > 0 : return "male"
    if gender < 0 : return "female"
    return "none"


print(get_gender('Сиденко Ирина Петровна'))
# -- Сиденко Ирина Петровна
# 0.0
# -1
# -1
# gender: -2.0
# female

print(get_gender('Хренова Гадя Петрович'))
# -- Хренова Гадя Петрович
# -0.5
# 0.0
# 1
# gender: 0.5
# male
```
Вообще адекватность алгоритма лучше оценивать на больших объемах, по одному-двум примерам трудно что-то сказать.

**Comment by FFire** [comment]
Все понятно, большое спасибо за помощь!

**Comment by insolor** [comment]
@FFire если вопрос решен, я думаю стоит закрыть issue. Вопросы по pymorphy2 как что-то сделать можно задавать на https://ru.stackoverflow.com, я там отвечаю (и не только я).
