### ISSUE TITLE
ValueError: Can't find a dictionary for language 'ru'. Installed languages: []. Try installing pymorphy2-dicts-ru package.

### ISSUE THREAD

**Issue by Pushikic** [kmike/pymorphy2#131]
Пару дней назад появилась ошибка: (словари установлены)
ValueError                                Traceback (most recent call last)
<ipython-input-10-119459716dc9> in <module>()
      1 import pymorphy2
      2 
----> 3 morph = pymorphy2.MorphAnalyzer()

2 frames
/usr/local/lib/python3.6/dist-packages/pymorphy2/analyzer.py in lang_dict_path(lang)
    127         "Can't find a dictionary for language %r. Installed languages: %r. "
    128         "Try installing pymorphy2-dicts-%s package." % (
--> 129             lang, list(lang_paths.keys()), lang
    130         )
    131     )

ValueError: Can't find a dictionary for language 'ru'. Installed languages: []. Try installing pymorphy2-dicts-ru package.

**Comment by buriy** [comment]
Хм, может всё же поставить русский словарь?

**Comment by Pushikic** [comment]
Ставил! Стало так после вчерашнего
обновления

пн, 21 сент. 2020 г., 23:43 Yuri Baburov <notifications@github.com>:

**Comment by Pushikic** [comment]
Во время установки pip install pymorphy2 видно что он словари устанавливает. Если поставить словарь вручную pip install -U pymorphy2-dicts-ru, то пишет что словарь еже установлен, и все равно выдает ошибку...

**Comment by buriy** [comment]
1) надо смотреть, что говорит pip freeze -- есть ли в путях проекты?
2) смотреть код для детекции, и пытаться его повторить -- где-то он ломается, видимо, и поэтому говорит, что не нашёл пакет со словарём.
в общем, явно какая-то проблема с установкой случилась, т.к. вряд ли кто-то менял логику работы пакетов.
т.е. в первую очередь надо попробовать деинсталлировать пакет, потом заново инсталлировать.
если не будет работать -- обновить виртуаленв или если работаете без venv, то удалить пакеты, связанные с питоном (pymorphy2), из системы руками, потом заново поставить.

**Comment by Pushikic** [comment]
Дело в том что это проводится в Google colab на виртуальной машине, каждый раз заново, И не у меня одного такая проблема. До позавчерашнего дня все работало. Спасибо!

**Comment by Pushikic** [comment]
Добавили же украинский язык, возможно, в файле /usr/local/lib/python3.6/dist-packages/pymorphy2/analyzer.py что то упустили

**Comment by Vyacheslav53** [comment]
Добрый день! И сегодня та же самая ошибка осталась. 
Pymorphy2 перестал запускаться именно после обновления, до этого работал.
Прошу исправить. Спасибо!

**Comment by dmitryzhelyabin** [comment]
Добрый день!
Также столкнулся с аналогичной ошибкой.
Работаю в той же среде, что и автор - в гугл колабе

Уважаемые разработчики библиотеки! Надеюсь на оперативное решение проблемы.
Уважаю Ваш труд и обожаю библиотеку. Без нее пока грустно. Удачи в решении!

**Comment by insolor** [comment]
@Pushikic "Дело в том что это проводится в Google colab на виртуальной машине, каждый раз заново" - недостаточно информации. Например, что за система на виртуальной машине? Только что развернул образ докер python:3.6, накатил pymorphy2 версии 0.9, никаких проблем не возникло.

**Comment by Pushikic** [comment]
> Добрый день!
> Также столкнулся с аналогичной ошибкой.
> Работаю в той же среде, что и автор - в гугл колабе
> 
> Уважаемые разработчики библиотеки! Надеюсь на оперативное решение проблемы.
> Уважаю Ваш труд и обожаю библиотеку. Без нее пока грустно. Удачи в решении!

Пока, нашли решение, установив предыдущую версию.

**Comment by insolor** [comment]
В общем, шаги для воспроизведения проблемы:
- Идем на https://colab.research.google.com
- Создаем новый блокнот (Файл -> Создать блокнот)
- В первой ячейке вбиваем:
```python
%%bash
pip install pymorphy2
```
- Дальше стандартно:
```python
import pymorphy2
```
```python
morphy = pymorphy2.MorphAnalyzer()
```
Получаем ошибку:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-f80ba70a1059> in <module>()
----> 1 morphy = pymorphy2.MorphAnalyzer()

2 frames
/usr/local/lib/python3.6/dist-packages/pymorphy2/analyzer.py in lang_dict_path(lang)
    127         "Can't find a dictionary for language %r. Installed languages: %r. "
    128         "Try installing pymorphy2-dicts-%s package." % (
--> 129             lang, list(lang_paths.keys()), lang
    130         )
    131     )

ValueError: Can't find a dictionary for language 'ru'. Installed languages: []. Try installing pymorphy2-dicts-ru package.
```
Скриншот:

![2020-09-24 15 49 21 colab research google com d92524986c56](https://user-images.githubusercontent.com/2442833/94147124-8d1bd500-fe7d-11ea-9bf3-364d893bfbb4.png)

Насколько удалось посмотреть, в модуле `analyzer.py` в функции `_lang_dict_paths` вызов `pkg_resources.iter_entry_points('pymorphy2_dicts')` почему-то возвращает пустой генератор:

![2020-09-24 15 52 47 colab research google com 6a6dc45f48e4](https://user-images.githubusercontent.com/2442833/94147520-0e736780-fe7e-11ea-9646-7144693a9903.png)

**Comment by insolor** [comment]
Что интересно, на pymorphy2==0.8 тоже возвращается пустой генератор, но анализатор при этом успешно инициализируется:

![2020-09-24 16 00 55 colab research google com ee958632a53c](https://user-images.githubusercontent.com/2442833/94148332-27c8e380-fe7f-11ea-9476-6b566a63c2b5.png)

**Comment by insolor** [comment]
В общем, после установки pymorphy2==0.9 в блокноте нужно перезапустить среду выполнения (меню "Среда выполнения" -> "Перезапустить среду выполнения"

**Comment by opennota** [comment]
> Что интересно, на pymorphy2==0.8 тоже возвращается пустой генератор, но анализатор при этом успешно инициализируется:

Потому что в 0.8 `iter_entry_points` не используется. Выпуск 0.8 состоялся, на минуточку, шесть лет назад, и после этого многое изменилось.

**Comment by insolor** [comment]
@opennota да, вы правы. Я только посмотрел, что analyzer.py был изменен 5 лет назад, а что предыдущий релиз был еще раньше, я не предполагал) В старой версии действительно `pkg_resources.iter_entry_points` не используется.

**Comment by Vyacheslav53** [comment]
> **Решение:** после установки pymorphy2==0.9 в блокноте нужно перезапустить среду выполнения (меню "Среда выполнения" -> "Перезапустить среду выполнения", после перезапуска среды словари успешно находятся:
> 
> ![2020-09-24 17 09 38 colab research google com 808379d4059c](https://user-images.githubusercontent.com/2442833/94156472-cad22b00-fe88-11ea-9612-bdf3554426ea.png)

После перезапуска среды выполнения ошибки нет, работает. Спасибо!

**Comment by kmike** [comment]
Спасибо за помощь в отладке @insolor! Думаю, https://github.com/kmike/pymorphy2/pull/132 исправит проблему. Сделаю релиз 0.9.1.

**Comment by Vyacheslav53** [comment]
Ошибки больше нет. Спасибо!
