### ISSUE TITLE
Обновление pymorphy2-dicts-ru до актуального состояния

### ISSUE THREAD

**Issue by victorbocharov** [kmike/pymorphy2#133]
Сейчас пакет основан на версии словаря 2017 года:

https://pypi.org/project/pymorphy2-dicts-ru/#history

**Comment by buriy** [comment]
@victorbocharov , кстати, а у вас можно как-то посмотреть, какие слова в opencorpora обновились за это время?

**Comment by victorbocharov** [comment]
@buriy вот так можно: http://opencorpora.org/dict_history.php 
Если нужно скриптом, то подходящего дампа, кажется, нет. Тогда можно взять SQL дамп и вытащить оттуда всё:
http://opencorpora.org/?page=downloads (внизу страницы)

**Comment by Shimorina** [comment]
скриптом тоже можно, если посмотреть на [номер ревизии](http://opencorpora.org/?page=export) лексем в xml-файле.
Нынешняя версия словарей pymorphy2 основывается на ревизии [404381](https://pypi.org/project/pymorphy2-dicts-ru/#history). Сейчас номер последней ревизии в словаре OpenCorpora 417127, то есть с тех пор произошло 12746 (417127-404381) правок.

**Comment by kmike** [comment]
Привет! Словарь обновил. Там поломался opencorpora-tools, и из-за этого словарь собирался неправильно.

**Comment by kmike** [comment]
По качеству - посмотрел дифф предсказаний, сюрпризов вроде нет; в словаре появилось больше имен людей.
