### ISSUE TITLE
Преобразование глаголов во времени и по роду работает некорректно

### ISSUE THREAD

**Issue by snowlue** [kmike/pymorphy2#134]
Преобразовывая глаголы к существительному при генерации предложений обнаружил, что преобразование по роду обращает глагол в прошедшее время. Дополнительное указание времени обращает глагол в причастие. Преобразование лишь во времени обращает глагол в деепричастие.

Таким образом получается, что форму глагола настоящего времени с родом получить никак нельзя.

```python
import pymorphy2
morph = pymorphy2.MorphAnalyzer(lang='ru')
word = morph.parse('толкать')[0]
print(word.inflect({'femn'}))
print(word.inflect({'pres'}))
print(word.inflect({'femn', 'pres'}))
```

Этот код должен выводить «толкает, толкает, толкает», но выводится «толкала, толкая, толкающий» (настоящее время глагола по умолчанию в мужском роде. Я попробовал по-другому: `word.inflect({'pres', 'VERB'})` — но такой вариант возвращает «толкаю» в 1-м лице. Попытки добавить туда граммему 'femn' приводят к тому, что inflect ничего не возвращает.

Как решить проблему и получить «толкает»?

> Подобная проблема уже прозвучала ранее в [этом](https://github.com/kmike/pymorphy2/issues/124) ишью, где вопрос ставился в обратную сторону, и у глагола начальной формой являлось причастие. Может, это даст какие-то наводки

**Comment by insolor** [comment]
Формы глагола по роду различаются только в прошедшем времени насколько я помню (ну и в форме деепричастия). В 3-м лице настоящего времени формы глагола по роду не будут различаться, и фактически не будут иметь категорию рода. Поэтому, когда вы ставите ограничение по роду - вы получаете формы, в которых род есть (прошедшее время).

`word.inflect({'femn', 'pres'}).word` у меня выводит "толкающая"

Если вам нужно 3-е лицо настоящего времени, то указывайте без рода: `word.inflect({'pres', '3per'}).word`

**Comment by snowlue** [comment]
О, не знал, что есть граммема «3per» — уж слишком их много. Знал, что в 3-м лице слова не различался, но не понимал, как мне его получить.

Да, насчёт пары `{'femn', 'pres'}` ошибся, там действительно «толкающая».

Спасибо большое за помощь. Проверил — действительно так. Ещё вопрос в этой же теме: есть ли какие-то примеры к граммемам, чтобы понять, как и когда их применять и когда они появляются?

**Comment by insolor** [comment]
Примеров не знаю, в данном случае скорее догадался, почему может не так работать (плюс опыт работы с Pymorphy2).
Ну и полный список граммем посмотрел, чтобы узнать, как 3-е лицо обозначается: http://opencorpora.org/dict.php?act=gram

**Comment by snowlue** [comment]
Да, список всех граммем мне известен, спасибо.
