### ISSUE TITLE
Нормализация ФИО

### ISSUE THREAD

**Issue by vzhilov** [kmike/pymorphy2#146]
Здравствуйте, 

Извлекаю из текста имена и фамилии и с помощью pyMorphy2 патыюсь их привести в начальный вид. 

```
import sys, pymorphy2
morph = pymorphy2.MorphAnalyzer()
p = morph.parse("Быковскую").normal_form
print(p)
```

На это мне выдаеются мужская фамилия Быковский. Это реально настроить?

**Comment by insolor** [comment]
Нормальная форма прилагательного (фамилии в данном случае) всегда в мужском роде. Нужно не брать нормальную форму, а просклонять (inflect) в именительный падеж (nominative - nomn):
```python
import pymorphy2

morph = pymorphy2.MorphAnalyzer()
word = "Быковскую"
p = morph.parse(word)[0]
print(p.inflect({'nomn'}).word)  # быковская
```

**Comment by vzhilov** [comment]
Уф, спасибо. Заработало. Скажите, а нет ли случайно функции развёртывать краткие имена в полные: 

`Дима => Дмитрий`

**Comment by insolor** [comment]
Нет, с точки зрения Pymorphy2 это разные слова (мне когда-то нужно было преобразовать существительное в прилагательное вида `дерево => деревянный`, но в Pymorphy2 возможности такого преобразования нет).

Можно посмотреть проект [petrovich](https://github.com/petrovich/pytrovich), возможно там что-то такое нет. Хотя сходу такого не нашел. Но возможно там можно как-то прикрутить свои правила преобразования.

**Comment by vzhilov** [comment]
Большое спасибо Вам
