### ISSUE TITLE
Проблема с постановкой рода

### ISSUE THREAD

**Issue by londrwus** [kmike/pymorphy2#163]
Нужно поставить имя Александра в творительный падеж.

Но проблема в том, что это имя распознается как мужское, поэтому нужно поставить в женский род.

`letter = morph.parse('Александра')[0].inflect({'ablt', 'femn'}).word`

Пытаюсь сделать с помощью 'femn', но происходит ошибка:

`letter = morph.parse(f'{name}')[0].inflect({'ablt', 'femn'}).word
AttributeError: 'NoneType' object has no attribute 'word'`

Если делать просто в женском роде:

`letter = morph.parse(f'{name}')[0].inflect({'femn'}).word
AttributeError: 'NoneType' object has no attribute 'word'`

**Comment by insolor** [comment]
Не используйте нулевой разбор. Если известно, что имя исходно в именительном падеже, отбирайте разборы в именительном падеже, потом уже берите первый (нулевой) разбор.

См. https://github.com/pymorphy2/pymorphy2/issues/152
