### ISSUE TITLE
Ошибки под высокой нагрузкой

### ISSUE THREAD

**Issue by uishnik** [kmike/pymorphy2#37]
Используем pymorphy2 на главной странице сайта. Под высокой нагрузкой сыпятся ошибки:

<pre>
File "/usr/local/lib/python2.7/dist-packages/pymorphy2/analyzer.py", line 135, in __init__
    self._units = [cls(self) for cls in units]

  File "/usr/local/lib/python2.7/dist-packages/pymorphy2/units/by_shape.py", line 57, in __init__
    self._tag = self.morph.TagClass(self.TAG_STR)

  File "/usr/local/lib/python2.7/dist-packages/pymorphy2/tagset.py", line 272, in __init__
    self._assert_grammemes_are_known(set(grammemes_tuple))

  File "/usr/local/lib/python2.7/dist-packages/pymorphy2/tagset.py", line 364, in _assert_grammemes_are_known
    raise ValueError("Grammemes are unknown: {%s}" % unknown_repr)

ValueError: Grammemes are unknown: {'ROMN'}
</pre>

При низкой нагрузке все нормально. С чем это может быть связано и что с этим делать?

**Comment by anti-social** [comment]
Лок должен быть глобальный:
```
lock = threading.RLock()

def f():
    with lock:
        do_thread_unsafe_operations()
```

А вообще, мне кажется, что там лок не нужен. Лучше, чтобы каждый анализатор имел свой набор тегов.

**Comment by kmike** [comment]
> Лучше, чтобы каждый анализатор имел свой набор тегов.

Ага, согласен, надо это переписывать, а не городить костыли.

**Comment by kmike** [comment]
@anti-social PR? :)

**Comment by anti-social** [comment]
Не понял вопрос.

**Comment by kmike** [comment]
может сделаешь PR с фиксом для лока? А то там сейчас и правда глупо написано.

**Comment by anti-social** [comment]
Просто я не знаю как фиксить. Я бы просто удалил =)
Или стоит переделать загрузку тегов?

**Comment by kmike** [comment]
если лок глобальным сделать, заработать ведь должно?

**Comment by anti-social** [comment]
Должно, но я не вижу в этом смысла. Проще в документации написать, что создание анализатора не потокобезопасное. Зачем создавать анализаторы в потоках?
