### ISSUE TITLE
неперехваченное исключение в 'opencorpora/reader.py'

### ISSUE THREAD

**Issue by KDruzhkin** [kmike/pymorphy2#48]
import opencorpora
corpus = opencorpora.CorpusReader('annot.opcorpora.xml')
tagged_words = corpus.iter_tagged_words()
for tw in tagged_words: pass    # на некотором шаге итерации вылетает исключение

**Comment by kmike** [comment]
Утащил в https://github.com/kmike/opencorpora-tools/issues/1.
