### ISSUE TITLE
Залить экспериментальный украинский словарь на pypi

### ISSUE THREAD

**Issue by kmike** [kmike/pymorphy2#56]

**Comment by irynkalytvynchuk** [comment]
Пытаюсь подготовить украинский словарь для Pymorphy2 на основе Opencorpora, не могли бы подсказать как перевести с формата XML в DAWG и каким образом потом можно попробовать использовать полученные данные в Pymorphy2?

**Comment by irynkalytvynchuk** [comment]
Пытаюсь подготовить украинский словарь для Pymorphy2 на основе Opencorpora, не могли бы подсказать как перевести с формата XML в DAWG и каким образом потом можно попробовать использовать полученные данные в Pymorphy2?

**Comment by IrynaPRL** [comment]
Пытаюсь подготовить украинский словарь для Pymorphy2 на основе Opencorpora, не могли бы подсказать как перевести с формата XML в DAWG и каким образом потом можно попробовать использовать полученные данные в Pymorphy2?

**Comment by kmike** [comment]
Сейчас схема такая. В [LanguageTool](https://github.com/languagetool-org/languagetool) есть украинский словарь, который готовит @arysin. Но там формат не совместим с OpenCorpora - например, нет разделения слов на лексемы. Тут в дело вступает @dchaplinsky со своим скриптом https://github.com/dchaplinsky/LT2OpenCorpora: @arysin отправляет словарь @dchaplinsky, @dchaplinsky преобразует его в формат OpenCorpora XML и присылает мне. А я с помощью скриптов https://github.com/kmike/pymorphy2-dicts умею компилировать словарь из формата OpenCorpora XML в формат, который понимает pymorphy2.

У меня сейчас есть одна довольно старая версия скомпилированного словаря, но @arysin просил ее особо не выкладывать пока никуда, т.к. она недостаточно хорошая. Насколько знаю, он подготовил новую версию и отправил ее @dchaplinsky, но у Димы пока не было времени с ней разобраться и отправить мне новую версию XML словаря, чтоб я ее выложил на pypi.

**Comment by kmike** [comment]
> Пытаюсь подготовить украинский словарь для Pymorphy2 на основе Opencorpora

А как?

**Comment by kmike** [comment]
из XML сконвертировать в фоомат, который понимает pymorphy2, можно с помощью скрипта https://github.com/kmike/pymorphy2-dicts/blob/master/build-dict.py. Надо установить все зависимости из https://github.com/kmike/pymorphy2-dicts/blob/master/requirements-build.txt, установить pymorphy2 с гитхаба и запустить

```
./build-dict.py --lang uk dict.xml new-dicts-folder 
```

**Comment by IrynaPRL** [comment]
Спасибо.
У меня входными данными являются Python программы с помощью которых можно генерировать парадигмы слов в XML формате, который аналогичен Opencorpora. Парадигмы генерируются согласно грамматического словаря украинского языка : http://www.burago.kiev.ua/index.php?option=com_content&view=article&id=134%3A-------140-000--&catid=19%3A2010-12-26-14-16-12&Itemid=21&lang=uk

**Comment by anti-social** [comment]
Похоже этот словарь не продается в электронном виде. Вы его сканировали и распознавали? 

Кстати, еще интересно не будет ли нарушением авторских прав оцифровать этот словарь и использовать в коммерческой разработке (без распространения самого словаря естественно)?

**Comment by grandsbor** [comment]
Извините, я просто мимо проходил, но довольно внезапно (в хорошем смысле) видеть, что кто-то использует формат нашего словаря :)

**Comment by IrynaPRL** [comment]
Нужен ваш совет!
Я уже подготовила словарь похож по структуре на опен корпора (установила все зависимости из https://github.com/kmike/pymorphy2-dicts/blob/master/requirements-build.txt, установила pymorphy2 с гитхаба и запустила), но теперь нужно зделать так, что бы он бил совместим с Pymorphy2.  Как можно это зделать? Как нужно изменить или переделать tagset что бы все получилось?

**Comment by IrynaPRL** [comment]
@kmike   
Нужен ваш совет!
 Я уже подготовила словарь похож по структуре на опен корпора (установила все зависимости из https://github.com/kmike/pymorphy2-dicts/blob/master/requirements-build.txt, установила pymorphy2 с гитхаба и запустила), но теперь нужно зделать так, что бы он бил совместим с Pymorphy2. Как можно это зделать? Как нужно изменить или переделать tagset что бы все получилось?

**Comment by kmike** [comment]
@IrynaPRL привет! А словарь уже собран (как написано [тут](https://github.com/kmike/pymorphy2/issues/56#issuecomment-92992892))?

**Comment by IrynaPRL** [comment]
@kmike да, это уже сделано, но не знаю что же делать дальше(

**Comment by IrynaPRL** [comment]
@kmike  да, это уже сделано, но не знаю что же делать дальше

**Comment by IrynaPRL** [comment]
@kmike Еще один вопрос, а возможно ли с полученного XML файла сгенерировать хэш таблицу или простое бинарное дерево? Пожалуйсто, подскажите возможно ли это и если да то как?

**Comment by kmike** [comment]
Чтоб попробовать экспериментальный словарь, можно выполнить

`$ pip install pymorphy2-dicts-uk`

и потом

```python
from pymorphy2 import MorphAnalyzer
m = MorphAnalyzer(lang='uk')
```

@IrynaPRL Изменить тегсет - что имеется в виду? Изменить его где - в pymorphy2, в словаре? 

Насчет хэш-таблицы - можно разобрать файл и загрузить его в питоний словарь. Структура XML описана на сайте OpenCorpora (http://opencorpora.org/?page=export), питоний код для разбора и предобработки есть тут: https://github.com/kmike/pymorphy2/tree/master/pymorphy2/opencorpora_dict. А зачем это нужно? Скрипт build_dict.py генерирует DAFSA, который точно так же можно использовать для получения значения по ключу.

**Comment by imposeren** [comment]
А когда планируется опубликовать на PyPI? Ато в документации `lang='uk'` уже есть, а использовать его еще нельзя

**Comment by kmike** [comment]
@imposeren он опубликован, им можно пользоваться; см. инструкцию: http://pymorphy2.readthedocs.org/en/latest/user/guide.html. Там еще некоторые доделки надо доделать, я, видимо, поэтому тикет не закрыл.

**Comment by imposeren** [comment]
@kmike, Я про сам pymorphy. Для пакетов которые ставятся через setup.py, использовать git проблематично. Есть `--process-dependency-links`, но у меня в Py3.4 это не сработало.

Какие issues блокируют публикацию? Я мог бы попытаться помочь, сделать Pull request

**Comment by dchaplinsky** [comment]
У меня поставилось и работает по инструкции.
Вот что хотелсь бы увидеть, так это обновленный словарь и частотный словарь. 

@kmike, давай замутим, а то я тебе пишу-пишу имейлы в имейлы и тишина.

**Comment by kmike** [comment]
@dchaplinsky да, давай, я почти ожил)

**Comment by dchaplinsky** [comment]
@kmike когда тебе будет удобно?

**Comment by kmike** [comment]
Словарь залит как pymorphy2-dicts-uk; информации о частотах там сейчас нет, но ее, похоже, нетривиально получить, хотя и можно. Я тикет закрою, т.к. экспериментальный словарь - на pypi.
