### ISSUE TITLE
Проверить PARTICLES_AFTER_HYPHEN для украинского языка

### ISSUE THREAD

**Issue by kmike** [kmike/pymorphy2#57]
В этой константе содержится список частиц, которые могут цепляться к словам через дефис.
См. https://github.com/kmike/pymorphy2/blob/master/pymorphy2/lang/uk/config.py и аналогичный список для русского (https://github.com/kmike/pymorphy2/blob/master/pymorphy2/lang/ru/config.py).

//сс @dchaplinsky @mariana-scorp

**Comment by imposeren** [comment]
"-то" как правило "переводится" как "лясь/сь": звідкилясь, чумусь, щось.

Но они все без дефиса -- такое надо куда-то заносить?

А теперь те что есть и с дефисом:
* "-но": Їдь-но
* "-таки": все-таки

**Comment by kmike** [comment]
@imposeren без дефиса - думаю, не надо. В русском бывает, что к слову частицу приписывают: "сделал-таки уроки", "сказать-то не мог?" и т.д.; этот список - для таких случаев. 

"все-таки", думаю, и так в словаре может быть.

**Comment by imposeren** [comment]
> В русском бывает, что к слову частицу приписывают: "сделал-таки уроки", "сказать-то не мог?" 

точно знаю только, что с "-но" такое можно делать: Їдь-но, лягай-но. И "-таки" вроде бы с таким же как и в русском использованием

**Comment by kmike** [comment]
@imposeren т.е. оставить -но и -таки?

**Comment by imposeren** [comment]
да

**Comment by kmike** [comment]
Спасибо!

**Comment by mariana-scorp** [comment]
Надо еще добавить "-бо" и "-от": "їж-бо", "який-бо", "так-от" тощо.

**Comment by kmike** [comment]
@mariana-scorp спасибо, добавил!
