### ISSUE TITLE
Проверить KNOWN_PREFIXES для украинского языка

### ISSUE THREAD

**Issue by kmike** [kmike/pymorphy2#58]
В этой константе содержатся префиксы, которые можно приписать к слову так, что его грамматические характеристики не изменятся. См. https://github.com/kmike/pymorphy2/blob/master/pymorphy2/lang/uk.py и аналогичный список для русского https://github.com/kmike/pymorphy2/blob/master/pymorphy2/lang/ru.py.

Сейчас там набор констант, взятый из LT. В LT они обрабатываются только если есть дефис, поэтому я добавил только варианты с дефисом. В русском списке есть префиксы и с дефисом, и без - может, в украинском тоже? Аналоги "не", "без", "до", "недо", "меж" и т.д.

//сс @dchaplinsky @mariana-scorp

**Comment by buriy** [comment]
Привет, лучше использовать двухбуквенное сокращение ua вместо uk для украинского языка. 
uk иногда используется для британского английского.

**Comment by kmike** [comment]
Там сначала ua и называлось, но я переименовал, т.к. uk - это по http://en.wikipedia.org/wiki/ISO_639-1. В википедии, LanguageTool, http://en.wikipedia.org/wiki/IETF_language_tag - везде "uk" используется.

**Comment by buriy** [comment]
Да, википедия именно uk, но в ISO3166 Украина объявлена как UA.

**Comment by kmike** [comment]
ISO3166 - это коды государств, а не для языков :P

**Comment by buriy** [comment]
А в OpenCorpora ещё недавно "пол (пол-, полу) хотели добавить в словарь префиксов (и ещё один какой-то)  -- их имеет смысл добавить в KNOWN_PREFIXES? У тебя есть только "полу" сейчас.
Есть https://github.com/OpenCorpora/opencorpora/issues/143, там в файлике совсем не полный список. "Пол-" почти к любому исчисляемому существительному ед. ч. можно добавить: полчеловека, полнеба, полвека, полозера, полкружки, полдуба. Особенно конечно к единицам измерения (полдуба, полвека, полкружки, полметра). Их как минимум полтысячи.
Как лучше это сделать?

**Comment by kmike** [comment]
Сообразить надо. Там UnknownPrefixAnalyzer много чего обработает без явного указания в списке для KnownPrefixAnalyzer. Пара моментов:

1. UnknownPrefixAnalyzer пробует разобрать остаток только как словарное слово; KnownPrefixAnalyzer сработает, даже если слово несловарное.

2. В настоящий момент если пользователь использует dawg-python (не dawg), то KnownPrefixAnalyzer работает за O(N) от длины своего списка префиксов.

**Comment by buriy** [comment]
Хм, прогнать огромный корпус через pymorphy2 + включенный UnknownPrefixAnalyzer и отфильтровать варианты от UnknownPrefixAnalyzer и неизвестные слова по префиксу "пол" ? А потом их добавить в OpenCorpora... неплохой вариант, надо попробовать.

**Comment by anti-social** [comment]
Почему бы `KNOWN_PREFIXES`, и возможно другие язоковые настройки не вынести в словарь?

**Comment by kmike** [comment]
@anti-social в этом есть смысл; сейчас `KNOWN_PREFIXES` в коде, т.к. мне неудобно словарь обновлять. Я стараюсь это делать осторожно - смотреть, что качество разбора не ухудшилось - т.к. там всякие тонкости бывают - поэтому делаю не очень часто. Ну и компиляция несколько минут занимает. А чтоб обновить только `KNOWN_PREFIXES` без обновления всего остального нужно либо иметь ту же самую копию исходного XML-словаря, либо обновлять словарь по частям. Ни то, ни другое сейчас делать неудобно, т.к. нет инструментов. Если настройки языка в коде, то проблем этих нет.

**Comment by kmike** [comment]
хотя я же и при обновлении `KNOWN_PREFIXES` смотрю, как разборы поменялись

**Comment by imposeren** [comment]
в Украинском аналогичные префиксы тоже могут быть использованы без дефиса. Например "Антимонопольний":
http://www.amc.gov.ua/amku/control/main/uk/index

Т.е. большинство префиксов из ru можно брать с минимальными изменениями. Вот так например:

```

KNOWN_PREFIXES = [
    "авіа", # авіаквиток
    "авто",# автоперетворювач
    "аква", # аквапарк
    "анти", # анимонопольній
    "анти-", # 
    "антропо", # антропогенний
    "архі", # архіважливий
    "арт", # 
    "арт-", # арт-майдан
    "астро", # астронавігація
    "аудіо", # аудіокнига
    "аеро", # аеромобільний
    "без", # безкоштовно
    "біо", # біометричний
    "вело", # велотренажер
    "взаємо", # взаємовиключний
    "поза", # позаплановий
    "внутрішньо", # внутрішньовенно
    "відео", # відеоспостереження
    "віце-", # 
    "вперед", # впередсмотрящий
    "гекто", # гектолітр
    "гелио", # геліоцентрична
    "гео", # геолокація
    "гетеро", # гетерохромия
    "гіга", # гігават
    "гігро", # гігроскопічність
    "гіпер", # гіперактивний
    "гіпо", # гіпоалергенний
    "гомо", # гомозигота
    "дво", # двонаправлений, двоповерховий
    "де", # декваліфікація
    "дез", # дезінфекція
    # "дека", # ???
    "деци", # дециметр
    "дис", # дисваліфікація
    "до", # доїхати
    "євро", # євробачення
    "за", # запрацювати
    "зоо", # зоомагазин
    "інтер", # інтерактивний
    "інфра", # інфрачервоний
    "квазі", # квазікристал
    "квазі-", # квазі-заходи
    "кіло", # кілограм
    "кіно", # кінокамера
    "контр", # контрзаходи
    "контр-", # контр-адмірал
    "космо", # космологія
    "космо-", # 
    "крипто", # криптозоологія
    "лейб-", # лейб-гвардія
    "лже", # лжерелігія
    "лже-", # лже-розтяжки
    "макро", # макросвіт
    # "макси", # ???
    # "макси-", #  ???
    "мало", # малоймовірний
    "між", # міжнаціональний
    "медіа", # медіапрогравач
    "медіа-", # 
    "мега", # мегават
    "мета", # метапрограмування
    "мета-", # 
    "метео", # метеосупутник
    "метро", # метросексуал
    "мікро", # мікросвіт
    "мілі", # міліграм
    "міні", # 
    "міні-", # 
    "моно", # моновалентна
    "мото", # мотоспорт
    "багато", # багатоповерховий
    # "мульті", # ???
    "нано", # нанометр
    "нарко", # наркозалежність
    "не", # ненадійний
    # "небез", # 
    # "недо", # 
    "нейро", # нейромедицина
    "нео", # 
    "низько", # низькокалорійний
    "обер-", # обер-офыцер
    "загально", # загальнонаціональний
    # "одно", # ???
    "навколо", # навколоплідний
    "орто", # ортофосфатна
    "палео", # 
    "пан", # панамериканський
    "пара", # паранормальний
    "пента", # 
    "пере", # переохолоджений
    "піро", # 
    "полі", # 
    "полу", # 
    "після", # післяопераційний
    "пост", # 
    "пост-", # 
    "порно", # 
    "пра", # прадід
    "пра-", # 
    "перед", # передбачення
    "прес-", # 
    "проти", # противірусні
    "проти-", # 
    "прото", # 
    "псевдо", # псевдокод
    "псевдо-", # 
    "радіо", # 
    "разно", # різнокаліберні
    "ре", # ревакцінація
    "ретро", # ретроактивний
    "ретро-", # 
    "само", # самонавідний
    "санти", # сантиметр
    "над", # надпровідний
    "над-", # 
    "спец", # 
    "суб", # субтропічний
    "супер", # суперпозиція
    "супер-", # 
    # "супра", # 
    "теле", # телеприсутність
    "тетра", # 
    "топ-", # 
    "транс", # трансатлантичний
    "транс-", # 
    "ультра", # ультрафіолет
    "унтер-", # 
    "штаб-", # штаб-квартира
    "екзо", # 
    "еко", # 
    "ендо", # 
    "економ-", # 
    "екс", # 
    "екс-", # 
    "екстра", # 
    "екстра-", # 
    "електро", # 
    "енерго", # 
    "етно", # 
]

```

**Comment by kmike** [comment]
@imposeren спасибо! А что думаешь про список префиксов, который из LT взят (https://github.com/kmike/pymorphy2/blob/master/pymorphy2/lang/uk/_prefixes.py)?

**Comment by imposeren** [comment]
На первый взгляд нормальные. Но все не перечитывал

По поводу возможности без дефиса: не малая часть из того списка ,без дефиса применяться не может
