### ISSUE TITLE
Неправильное определение нормальной формы слова

### ISSUE THREAD

**Issue by sklprogs** [kmike/pymorphy2#63]
Добрый день. Пользуюсь Вашей программой уже достаточно долгое время и безмерно рад результату. Тем не менее, иногда встречаются ошибки. Например, нужно найти нормальную форму для слова "опору" (или "опоре"). Я предполагаю получить "опора", однако
morph.parse('опору')[0].normal_form
и
morph.parse('опору')[0].inflect({'sing','nomn'}).word
выдают "опор".
Аналогичная ситуация со словом "гиалуроновой" (гиалуроновая кислота):
morph.parse('гиалуроновую')[0].inflect({'sing','nomn'}).word
'гиалуроновая'
НО:
morph.parse('гиалуроновой')[0].inflect({'sing','nomn'}).word
'гиалуронова'
morph.parse('гиалуроновой')[0].normal_form
'гиалуронов'
Это баг или я что-то не так делаю?

**Comment by kmike** [comment]
Добрый день.

Проблема в том, что для того, чтобы определить нормальную форму слова, нужно сначала выбрать правильный разбор из предложенных. 

Например, разберем слово "гилауроновой":

```
In [21]: m.parse('гиалуроновой')
Out[21]: 
[Parse(word='гиалуроновой', tag=OpencorporaTag('NOUN,anim,femn,Sgtm,Surn sing,gent'), normal_form='гиалуронов', score=0.19050802139037432, methods_stack=((FakeDictionary(), 'гиалуроновой', 36, 7), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('NOUN,anim,femn,Sgtm,Surn sing,datv'), normal_form='гиалуронов', score=0.19050802139037432, methods_stack=((FakeDictionary(), 'гиалуроновой', 36, 8), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('NOUN,anim,femn,Sgtm,Surn sing,ablt'), normal_form='гиалуронов', score=0.19050802139037432, methods_stack=((FakeDictionary(), 'гиалуроновой', 36, 10), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('NOUN,anim,femn,Sgtm,Surn sing,loct'), normal_form='гиалуронов', score=0.19050802139037432, methods_stack=((FakeDictionary(), 'гиалуроновой', 36, 11), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('ADJF femn,sing,gent'), normal_form='гиалуроновый', score=0.05949197860962567, methods_stack=((FakeDictionary(), 'гиалуроновой', 10, 8), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('ADJF femn,sing,datv'), normal_form='гиалуроновый', score=0.05949197860962567, methods_stack=((FakeDictionary(), 'гиалуроновой', 10, 9), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('ADJF femn,sing,ablt'), normal_form='гиалуроновый', score=0.05949197860962567, methods_stack=((FakeDictionary(), 'гиалуроновой', 10, 11), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой'))),
 Parse(word='гиалуроновой', tag=OpencorporaTag('ADJF femn,sing,loct'), normal_form='гиалуроновый', score=0.05949197860962567, methods_stack=((FakeDictionary(), 'гиалуроновой', 10, 13), (KnownSuffixAnalyzer(min_word_length=4, score_multiplier=0.5), 'новой')))]
```

pymorphy2 предлагает несколько вариантов разбора - в данном случае как фамилию Гилауронов (первые 4 варианта) или как прилагательное "гилауроновый" (последние 4 варианта). 

В общем случае брать первый предложенный вариант разбора (`morph.parse('гиалуроновой')[0]`) лучше, чем любой другой, т.к. pymorphy2 старается отсортировать слова по убыванию вероятности разбора. Но во-первых, это далеко не всегда работает, а во-вторых - правильный разбор невозможно выбрать, имея только отдельное слово; нужно еще учитывать контекст, а pymorphy2 работает только с отдельными словами.

Вывод тут такой - если не снимать неоднозначность разбора или снимать ее неточно, то ошибки будут всегда.

Как неоднозначность снимать - вопрос открытый. Это могут быть какие-то статистические модели (но нужен размеченный корпус текстов), или это могут быть какие-то специфичные для задачи правила. Ну, например, если вы знаете, что в тексте нет фамилий, то можно занижать вероятности разбора слова как фамилии. Или, например, если слово не с заглавной буквы, то вероятность того, что это фамилия - гораздо меньше.

С "опору" все сложнее из-за того, что вероятность правильного разбора оценивается по корпусу OpenCorpora, а слова "опор" и "опора" оба редкие, так что вряд ли корпус поможет. Тут должно помочь контекстное снятие неоднозначности. 

Для снятия неоднозначности на основе контекста я потихоньку делаю https://github.com/kmike/morphine, но там еще довольно далеко до чего-то такого, что можно было бы рекомендовать по умолчанию.

**Comment by sklprogs** [comment]
Спасибо за подробный ответ. Скажите, пожалуйста, а вот это:
morph.parse('существенные')[0].inflect({'plur','accs'}).word
'существенных'
- тоже контекстный случай? Я просто занимаюсь склонением фраз, и в винительном падеже вместо "существенные признаки" получаю "существенных признаки".
Возможно ли склонять фразы целиком, или этим будет заниматься morphine?

**Comment by buriy** [comment]
Привет, склонение винительного падежа в данной ситуации зависит от
одушевлённости, ср.:
вижу существенные признаки
вижу существенных людей
вижу порядочных людей
вижу порядочные признаки
итп.

inflect не знает, что одно слово в данной ситуации зависит от другого (это
задача синтаксического анализа), поэтому pymorphy не может понять и
перенести признак одушевлённости с существительного на прилагательное.

2015-05-02 23:57 GMT+06:00 sklprogs <notifications@github.com>:

> Спасибо за подробный ответ. Скажите, пожалуйста, а вот это:
> morph.parse('существенные')[0].inflect({'plur','accs'}).word
> 'существенных'
>
>    - тоже контекстный случай? Я просто занимаюсь склонением фраз, и в
>    винительном падеже вместо "существенные признаки" получаю "существенных
>    признаки". Возможно ли склонять фразы целиком, или этим будет заниматься
>    morphine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmike/pymorphy2/issues/63#issuecomment-98382854>.
>



-- 
Best regards, Yuri V. Baburov, Skype: yuri.baburov

**Comment by sklprogs** [comment]
Нормальная форма для "п" (просто аббревиатура "параграфа", но без точки) выдается как "плата". Это как? ;-)

**Comment by kmike** [comment]
з.п. - заработная плата. С точкой или без точки - pymorphy2 не знает, т.к. работает с отдельными токенами.

**Comment by sklprogs** [comment]
"П" может означать что угодно, не обязательно "плата", например, "поселок", "параграф" и т.п. Почему бы не возвращать то, что на входе, если есть неясность?

**Comment by kmike** [comment]
Да, в случае с "п" может иметь смысл возвращать нормальную форму "п". Но я не очень понимаю, как сделать это, и сохранить другие фичи pymorphy2 (например, возможность развернуть форму из краткой в полную, хотя бы даже просто для того, чтоб понять, почему возвращается NOUN,inan,femn,Fixd,Abbr sing,nomn). Если есть какие-то конкретные предложения - welcome :)

**Comment by buriy** [comment]
Привет,

А почему бы не сделать совсем отдельный метод для сокращений, если уж
хочется?

"п" -- может быть "П.", а оно может быть и "Петровна", и "Петровне", и
"Петровну", и даже "Павловичем" -- таким образом, угадать падеж или другую
морфологическую характеристику таким способом не представляется возможным.

Мне кажется, имеет смысл предоставить большую гибкость в войне с
сокращениями, и предоставить пользователю составить отдельный список для
его сокращений.

Я вообще вижу в pymorphy2 прикладную функцию определения грамматической
формы, получения нормальной формы, компактного хранения словаря и перевода
слов в другую грамматическую форму.
Сокращения, таким образом, не попадают в данную область деятельности.



2015-05-18 22:18 GMT+06:00 Mikhail Korobov <notifications@github.com>:

> Да, в случае с "п" может иметь смысл возвращать нормальную форму "п". Но я
> не очень понимаю, как сделать это, и сохранить другие фичи pymorphy2
> (например, возможность развернуть форму из краткой в полную, хотя бы даже
> просто для того, чтоб понять, почему возвращается NOUN,inan,femn,Fixd,Abbr
> sing,nomn). Если есть какие-то конкретные предложения - welcome :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmike/pymorphy2/issues/63#issuecomment-103117269>.
>



-- 
Best regards, Yuri V. Baburov, Skype: yuri.baburov

**Comment by sklprogs** [comment]
Добрый день, buriy. Я считаю, что pymorphy2 должен оставаться юниксвейным инструментом, а не превращаться в швейцарский нож. Если есть неоднозначность, можно просто вывести предупреждение, а в результат поставить None или оставить то, что на входе. Что-то додумывать точно не надо, это усложняет алгоритмы и ведет к ошибкам. Подобные ситуации лучше регулировать, указывая соответствующие алгоритмы при склонении. Если нужно обеспечить юзер-френдли, можно просто сделать, например, GUI-надстройку, которая, основываясь на предупреждениях pymorphy2, будет выдавать нужные варианты. Сам же pymorphy2 должен ориентироваться на полную автоматизацию, а не внешний ввод каких-то вариантов или что-то додумывать. Например, моя программа использует pymorphy2 для извлечения одинаковых фрагментов (возможны разные склонения) из параллельных текстов. Слов много, каждое преобразуется в нормальную форму (чтобы не тратить время на поиск по всем падежам). При этом, если что-то не так пошло в pymorphy2, отдебажить результат сложно, я не сразу пойму, где ошибка - в моих алгоритмах или непосредственно в склонении. Однако, если бы я получал тот же результат, что на входе, или None, или даже ошибку, все было бы предельно ясно.

**Comment by buriy** [comment]
skiprogs, эмм... а как это противоречит тому, что я сказал?

**Comment by kmike** [comment]
Я пока склоняюсь к тому, что @sklprogs прав, и лучше убрать возможность склонять между полной и краткой формой слова, но зато нормализовывать сокращения в сокращения. Для этого надо вот [сюда](https://github.com/kmike/pymorphy2/blob/174662e229535cba7ae06360d14d41c943175b3a/pymorphy2/opencorpora_dict/compile.py#L211) добавить цифру 21 (FULL-CONTRACTED) и пересобрать словарь.

**Comment by GraphGrail** [comment]
А можно ли задачу определения нормальной формы слова решить обновлением словарей?
Например `morph.parse('грааля')[0].normal_form`  упорно выдает также "грааля", а не "грааль"
При этом второй по вероятности вариант уже правильный:  `morph.parse('грааля')[1].normal_form`  выдает "грааль".

**Comment by kmike** [comment]
1. Ошибки будут всегда, поэтму я тикет закрываю. Но, наверное, нужно бы документацию обновить, чтоб понятнее было, в чем дело.
2. Возможность склонения между сокращенными и полными формами убрал.
3. @BitcoinKing обновлением словаря это решить можно - нужно в словарь OpenCorpora добавить слово Грааль. Создал тикет: https://github.com/OpenCorpora/opencorpora/issues/779.
