### ISSUE TITLE
Заснеженный и заснежённый

### ISSUE THREAD

**Issue by insolor** [kmike/pymorphy2#64]
Добрый день!
Есть слово заснеженный, получаю от него объект parse:
``` python
>>> morph.parse('заснеженный')[0]
Parse(word='заснеженный', tag=OpencorporaTag('ADJF,Qual masc,sing,nomn'), normal_form='заснеженный', score=0.25, methods_stack=((DictionaryAnalyzer(), 'заснеженный', 1539, 0),))
```

Теперь пробую его просклонять:
``` python
>>> morph.parse("заснеженный")[0].inflect({'femn', 'datv'})
Parse(word='заснежённой', tag=OpencorporaTag('ADJF,Qual femn,sing,datv,Infr'), normal_form='заснеженный', score=1.0, methods_stack=((DictionaryAnalyzer(), 'заснежённой', 1539, 18),))
```

Получаю "заснежённой", хотя предполагал получить "заснеженной".
Парсим "заснеженной":
``` python
>>> morph.parse("заснеженной")[0]
Parse(word='заснеженной', tag=OpencorporaTag('ADJF,Qual femn,sing,gent'), normal_form='заснеженный', score=0.125, methods_stack=((DictionaryAnalyzer(), 'заснеженной', 1539, 17),))
```

Видим, что такая форма есть (хотя первым попавшимся оказался не дательный, а родительный падеж), но без Infr.

Смотрим, что за Infr:
``` python
>>> morph.parse("заснеженной")[0].tag.cyr_repr'
ПРИЛ,кач жр,ед,рд'
>>> morph.parse("заснежённой")[0].tag.cyr_repr'
ПРИЛ,кач жр,ед,рд,разг'
```

Разг - разговорное. Как мне просклонять, чтобы в результате получить не разговорную форму, а "правильную"?

**Comment by kmike** [comment]
Добрый день! 

В общем случае - есть метод p.lexeme, через который можно получить все формы слова (см. http://pymorphy2.readthedocs.org/en/latest/user/guide.html#inflection). Просклонять - значит найти среди них форму с нужными граммемами. Т.е. можно нужную логику написать вручную, если "зашитая" в .inflect не подходит. Метод inflect это и делает - выбирает из всех форм те (ту), в которой есть нужные граммемы. Реализацию можно глянуть [тут](https://github.com/kmike/pymorphy2/blob/174662e229535cba7ae06360d14d41c943175b3a/pymorphy2/analyzer.py#L330).

Но я понимаю, что это плохой ответ :) Хотелось бы, чтоб все просто работало. Первым шагом, видимо, можно в pymorphy2 в метод inflect добавить новый аргумент с граммемами, которых в форме быть *не* должно (или которых видеть не хотелось бы). Наверное, еще что-то придумать можно, но пока не могу сообразить.

**Comment by insolor** [comment]
@kmirke, пока и так сойдет. В общем случае pymorphy2 работает как надо, для частных случаев добавляю исключения.
Еще такой вопрос (не в тему), есть ли простой способ преобразования существительного в прилагательное по типу "дуб"->"дубовый", "сталь"->"стальной"?

**Comment by kmike** [comment]
> Еще такой вопрос (не в тему), есть ли простой способ преобразования существительного в прилагательное по типу "дуб"->"дубовый", "сталь"->"стальной"?

В словаре OpenCorpora сейчас отсутствует информация о связях между существительными и прилагательными, поэтому pymorphy2 тут никак не поможет. Простого способа не знаю. 

В идеале - какие-то автоматические правила написать, чтоб большую часть таких пар в словаре найти (в духе "если есть СУЩ ..., и есть ПРИЛ ...вый, то добавить связь"), потом все вычитывать вручную, а потом в словарь эти данные добавить.

**Comment by insolor** [comment]
Вообще, можно попробовать в similarity() сделать что-то вроде `return len(grammemes & tag.grammemes) - len(grammemes ^ tag.grammemes) * 0.5`
Тогда варианты с "лишними" граммемами будут отсеиваться, а если я все-таки вдруг захочу разговорную форму, то в inflect так и скажу, что мне нужен 'Infr'.

**Comment by kmike** [comment]
Я вроде что-то такое пытался делать (без коэффициента 0.5), но были проблемы. Сейчас пример не приведу, но с `len(grammemes ^ tag.grammemes)` все работало не очень хорошо. Возможно, из-за того, что если в лексеме есть несколько частей речи, то между ними `len(grammemes ^ tag.grammemes)` будет иметь большое значение. Или из-за того, что некоторые граммемы в тегах опускаются (anim/inan вроде не всегда пишутся), если они и так понятные. Не помню :) Мне идея нравится, но с ней нужно посидеть и посмотреть, как она работает для разных случаев. Может, коэффициент 0.5 все поправит.

**Comment by insolor** [comment]
Тут даже коэффициента 0.1 будет достаточно.

По поводу одушевленностии-неодушевленности - у меня "шёлковый" и "медный" добавлены в исключения как раз из-за того, что pymorphy2 в винительном падеже их превращает "шёлкового" и "медного". Указание не помогает. Приходится склонять своими велосипедами, по самопальной табличке окончаний.

**Comment by insolor** [comment]
Ах вот в чем проблема, он не может просклонять медный и шёлковый в форму женского рода в винительном падеже:

```Python
In [16]: morph.parse("медный")[0].inflect({'accs', 'masc', 'inan'})

Out[16]: Parse(word='медный', tag=OpencorporaTag('ADJF,Qual inan,masc,sing,accs'), normal_form='медный', score=1.0, methods_stack=((DictionaryAnalyzer(), 'медный', 12, 4),))

In [22]: print(morph.parse("медный")[0].inflect({'accs', 'femn', 'inan'}))
None

In [20]: morph.parse("медный")[0].inflect({'accs', 'femn'})

Out[20]: Parse(word='медную', tag=OpencorporaTag('ADJF,Qual femn,sing,accs'), normal_form='медный', score=1.0, methods_stack=((DictionaryAnalyzer(), 'медную', 12, 10),))

In [24]: morph.parse("шёлковый")[0].inflect({'accs', 'masc', 'inan'})

Out[24]: Parse(word='шёлковый', tag=OpencorporaTag('ADJF,Qual inan,masc,sing,accs'), normal_form='шёлковый', score=1.0, methods_stack=((DictionaryAnalyzer(), 'шёлковый', 3061, 8),))

In [25]: print(morph.parse("шёлковый")[0].inflect({'accs', 'femn', 'inan'}))
None
```

**Comment by bzaar** [comment]
Насчет связей сущ-прил, их есть немного (несколько сотен) на http://odict.ru, тег #HUB. Там в основном прилагательные на -ский (Москва - московский). В общем случае от одного существительного бывает много прилательных (свинья - свиной, свинячий, свинский и даже свиний). Вам нужны именно пары "материал - сделанный из такого материала"?

**Comment by insolor** [comment]
@bzaar, да, замена вида "из меди" - "медный". Металлы, дерево, минералы, и т.д. Пока обхожусь просто питоновским словарем, наверное пока так и оставлю.

**Comment by bzaar** [comment]
@insolor, Да, зачем менять, если и так работает? А можете прислать свой словарик, я его добавлю к odict.ru? Адрес: ss @ одикт.ру :)

**Comment by insolor** [comment]
@bzaar, словарик там прямо в коде. Собственно, вот: https://bitbucket.org/dfint/changetextpy_script/src/42e606120dcefb6afa36ec7aa427ed4f14923efd/changetext.py?at=pymorphy2#cl-558
Возможно что-то из этого пригодится, хотя там много лишнего намешано. Остальной код лучше не смотреть, он более чем ужасен, его еще чистить и чистить  :)
Если интересно, это часть вот этого проекта:
https://bitbucket.org/insolor/dfrus

**Comment by insolor** [comment]
Сделал себе такую функцию, пока все работает:

```Python
def custom_inflect(form, required_grammemes):
    self = form._morph
    possible_results = [f for f in self.get_lexeme(form)
                        if required_grammemes <= f[1].grammemes]

    if not possible_results:
        required_grammemes = self.TagClass.fix_rare_cases(required_grammemes)
        possible_results = [f for f in self.get_lexeme(form)
                            if required_grammemes <= f[1].grammemes]

    grammemes = form[1].updated_grammemes(required_grammemes)
    def similarity(frm):
        tag = frm[1]
        return len(grammemes & tag.grammemes) - len(grammemes ^ tag.grammemes) * 0.1
    res = heapq.nlargest(1, possible_results, key=similarity)
    return None if not res else res[0]
```

**Comment by insolor** [comment]
Вчера снова столкнулся с похожей проблемой - на этот раз это было слово "ведро", которое по-умолчанию склоняется опять же по разговорному варианту (как "вёдро"). Более того, основной формой считается именно разговорная. Но тут проблема скорее в том, что совершенно разные слова [ведро](https://ru.wiktionary.org/wiki/%D0%B2%D0%B5%D0%B4%D1%80%D0%BE) и [вёдро](https://ru.wiktionary.org/wiki/%D0%B2%D1%91%D0%B4%D1%80%D0%BE) в словаре opencorpora считаются одним и тем же.
Локально у себя проблему решил использованием функции custom_inflect() из комментария выше.
