### ISSUE TITLE
Код украинского языка ua, а не uk

### ISSUE THREAD

**Issue by worldmind** [kmike/pymorphy2#68]
В юзергайде почему-то uk

**Comment by insolor** [comment]
Ошибаетесь, см. [https://ru.wikipedia.org/wiki/Украинский_язык](https://ru.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA) в табличке справа, код языка по ISO 639-1 - **uk**.

**Comment by worldmind** [comment]
Да, извиняюсь, коды языка и стран не одно и тоже, хотя это конечно путает
