### ISSUE TITLE
Нормальная форма для отчеств

### ISSUE THREAD

**Issue by whalebot-helmsman** [kmike/pymorphy2#73]
Сейчас в качестве нормальной формы для отчеств, выдается имя от которого это отчество образовано, это немного неожиданно
```

pymorphy2.MorphAnalyzer().parse('Оскарович')
[Parse(word='оскарович', tag=OpencorporaTag('NOUN,anim,masc,Patr sing,nomn'), normal_form='оскар', score=1.0, methods_stack=((<DictionaryAnalyzer>, 'оскарович', 26, 12)
,))]
pymorphy2.MorphAnalyzer().parse('Иванович')
[Parse(word='иванович', tag=OpencorporaTag('NOUN,anim,masc,Patr sing,nomn'), normal_form='иван', score=1.0, methods_stack=((<DictionaryAnalyzer>, 'иванович', 1620, 12),
))]

```

**Comment by kmike** [comment]
Хм, я думал, что вот тут починил: https://github.com/kmike/pymorphy2/commit/f69c0d1067e223d2cd282d4712bdcd767b88d99c, но, похоже, что нет.

**Comment by whalebot-helmsman** [comment]
А возможно и починили, только в pypi старые версии

```

DAWG-Python==0.7.2
docopt==0.6.2
pymorphy2==0.8
pymorphy2-dicts==2.4.393442.3710985

```

**Comment by kmike** [comment]
> А возможно и починили, только в pypi старые версии

Я вроде проверил, в новой тоже не сработало.

> И сразу вопрос: код можно с github поставить, а откуда брать свежие словари

Свежие словари поставятся автоматически, если поставить код с гитхаба. Пакеты со словарями теперь называются pymorphy2-dicts-ru (русский) и pymorphy2-dicts-uk (украинский), но работают они только с версией с гитхаба.

**Comment by dveselov** [comment]
Раз уж тут зашел разговор про новые версии и словари.
Михаил, есть ли вероятность увидеть pymorphy2 версии 0.9 и словари посвежее (последнее обновление - полтора года назад) на pypi в ближайшее время?

**Comment by kmike** [comment]
@whalebot-helmsman нет, я ошибся в комментарии выше; с обновленным словарем и версией из master все работает. Так что я тикет закрываю.

@dveselov словари я обновил (https://pypi.python.org/pypi/pymorphy2-dicts-ru/ - они только для версии из master). Над релизом еще немного поработать надо, но я хочу более-менее скоро его сделать. Думал сегодня, но не успеваю - может, на следующих выходных постараюсь, или на неделе.
