### ISSUE TITLE
Получить все слова в начальной форме и все их формы

### ISSUE THREAD

**Issue by niXman** [kmike/pymorphy2#74]
Здравствуйте!

В общем-то сабж.
Т.е. хотелось бы получить что-то типа:
`<слово в начальной форме>:(спиок всех форм слова)`

Спасибо.

**Comment by grandsbor** [comment]
Для русского языка можно взять прямо у нас: http://opencorpora.org/files/export/dict/dict.opcorpora.txt.bz2. Формат немного другой, но plain text, вас должен устроить

**Comment by bzaar** [comment]
Или у нас :)  http://odict.ru/download/odict.csv.zip

**Comment by niXman** [comment]
@bzaar так и сделал. и прогнал через скрипт чтоб удалить повторы из форм.

спасибо, вопрос закрыт.

**Comment by mikhail-barg** [comment]
Хотелось бы переоткрыть этот тикет. С точки зрения полноты, ODict мал (попробуйте например найти в нем слово "десять"). OpenCorpora конечно больше но тоже ограничен. В то время как PyMorphy позволяет строить формы для отсутствующих изначально слов.

**Comment by mikhail-barg** [comment]
По идее наверное это делается вот так:

```
parseList = morph.parse(word);
		for parse in parseList:
			lexeme = parse.lexeme;
			for form in lexeme:
				print(form.word)
```

**Comment by niXman** [comment]
`parseList = morph.parse(word);`

допустим. но откуда взять слова в начальной форме?

**Comment by opennota** [comment]
``` python
# -*- coding: utf-8 -*-
from dawg_python import RecordDAWG
from pymorphy2 import MorphAnalyzer, units

path = '/usr/local/lib/python2.7/dist-packages/pymorphy2_dicts_ru/data'

m = MorphAnalyzer(path=path, units=[units.DictionaryAnalyzer()])

d = RecordDAWG(str('>HH'))
d.load(path + '/words.dawg')

seen = set()
for word in d.iterkeys():
    for p in m.parse(word):
        if p.normal_form not in seen:
          seen.add(p.normal_form)
          print p.normal_form

```
Например.

**Comment by kmike** [comment]
Там еще есть метод [MorphAnalyzer.iter_known_word_parses](http://pymorphy2.readthedocs.io/en/latest/misc/api_reference.html#pymorphy2.analyzer.MorphAnalyzer.iter_known_word_parses), который все разборы из словаря возвращает.
