### ISSUE TITLE
Can't install on Google App Engine

### ISSUE THREAD

**Issue by jhw** [kmike/pymorphy2#82]
Hi,

I'd really like to be able to use this with Google App Engine

The normal way to do this on App Engine is to install locally via pip

` pip install -t lib git+git://github.com/kmike/pymorphy2.git`

Then add an 'appengine_config.py' file into your root

```
from google.appengine.ext import vendor
vendor.add('lib')
```

However if I do this I get the following at runtime

```
 File "/home/jhw/work/russkiwol/lib/pymorphy2/analyzer.py", line 105, in _lang_dict_paths
    import pkg_resources
ImportError: No module named pkg_resources
```

And even if I add pkg_resources.py to /lib, I get the following

```
  File "/home/jhw/work/russkiwol/lib/pymorphy2/analyzer.py", line 129, in lang_dict_path
    lang, list(lang_paths.keys()), lang
ValueError: Can't find a dictionary for language u'ru'. Installed languages: []. Try installing pymorphy2-dicts-ru package.
```

Am guessing the problem here is that App Engine uses its own non- standard environment, paths etc. I'm not even sure pymorphy2 would work on App Engine, given the restrictions. But wondering if this is fixable, or how much work it might take to get it working on App Engine ?

Great project BTW

Thx!

**Comment by kmike** [comment]
Hey! I'm not familiar with AppEngine, but if you want to avoid using loading dictionary by laguage name (which seems to fail on AppEngine) it should be possible to load the dictionary data by path. 

If you download and unpack tar.gz file from https://pypi.python.org/pypi/pymorphy2-dicts-ru then actual dictionary data would be in 'pymorphy2_dicts_ru/data' folder - the package is just a wrapper to make data pip-installable. You can put this folder somewhere (e.g. to `/var/pymorphy2_dicts_ru/data`) and then create MorphAnalyzer instance like this: `MorphAnalyzer(path="/var/pymorphy2_dicts_ru/data", lang="ru")`. This way installing pymorphy2-dicts-ru package shouldn't be required. Hope this helps!

**Comment by jhw** [comment]
Works! Thanks!

#closed
