### ISSUE TITLE
Определение имени человека

### ISSUE THREAD

**Issue by skiesx** [kmike/pymorphy2#83]
Можно ли с помощью данной библиотеки определить - является слово именем человека или нет? Языки русский и украинский. Заранее спасибо) Тут просто не нашел такого - https://pymorphy2.readthedocs.io/en/latest/index.html .

**Comment by kmike** [comment]
Привет. В OpenCorpora имена отмечены пометкой Name (см. http://pymorphy2.readthedocs.io/en/latest/user/grammemes.html), т.е. можно написать что-то вроде

```py
is_name = any('Name' in p.tag for p in morph.parse(word))
```
Если какого-то имени нет в OpenCorpora (а это бывает, особенно с уменьшительно-ласкательными вроде "Алёшенька"), можно завести тикет тут: https://github.com/OpenCorpora/opencorpora/issues

В украинском словаре вроде этой пометки нет.

Если бы мне эту задачу надо было решать на практике, я бы в дополнение к pymorphy2 постарался еще найти/скачать откуда-нибудь списки имен.

**Comment by skiesx** [comment]
Спасибо)

**Comment by skiesx** [comment]
Спасибо)
