### ISSUE TITLE
Разбор слова по составу

### ISSUE THREAD

**Issue by deepmipt-VladZhukov** [kmike/pymorphy2#85]
Хотелось бы уметь получить список морфем для слова. Можно ли это сделать с помощью pymorphy2? Судя по документации, MorphAnalyzer должен уметь такое делать.

**Comment by kmike** [comment]
Нет, так не получится - в словаре этой информации нет. При компиляции словаря в компактную форму слова делятся на части, но это не морфемы в лингвистическом смысле, а просто детали реализации.

**Comment by deepmipt-VladZhukov** [comment]
Спасибо. А есть какое-то решение для этой задачи? (пробовал morfessor, но на русском он как-то плохо у меня работает)

**Comment by kmike** [comment]
Не, не видел такого. Видимо, что-то придумывать надо.

**Comment by bzaar** [comment]
Для решения этой задачи необходим словообразовательный словарь, вроде вот этого: http://old.kpfu.ru/infres/slovar1/ 

В машинно-читаемом виде я их пока не видел. Из бумажных наиболее полный, насколько я знаю, Тихонова:

А.Н. Тихонов Словообразовательный словарь русского языка в двух томах: Ок 145000 слов. - М. "Русский язык" 1985. - 1 том 854 с., 2 том 885 с.

А для чего понадобилось решение этой задачи, если не секрет?

**Comment by deepmipt-VladZhukov** [comment]
Не секрет. Хочется для вот этой модели: https://github.com/rguthrie3/MorphologicalPriorsForWordEmbeddings
получить разумные морфемы (они в принципе иногда даже нормальные получаются предложенным морфессором, но хотелось бы лучше)

**Comment by deepmipt-VladZhukov** [comment]
Вроде нашел что-то похожее, пока не пробовал
http://polyglot.readthedocs.io/en/latest/Installation.html
