### ISSUE TITLE
Английский язык

### ISSUE THREAD

**Issue by ins2718** [kmike/pymorphy2#86]
Доброго времени суток, подскажите пожалуйста, есть ли возможность разбора английских слов? На удивление не нашёл ни одной библиотеки под python3 способной менять формы глаголов.

**Comment by kmike** [comment]
Привет. Теоретически, вроде добавить можно; данные взять, например, из wordnet (?). Но это может быть довольно много работы, втч может понадобиться какие-то часть pymorphy2 отрефакторить.

**Comment by ins2718** [comment]
Насколько я понял wordnet ничего о временах не знает, т.е. wrote и written можно превратить в инфинитив, но не наоборот.

**Comment by kmike** [comment]
Еще есть http://www.clips.ua.ac.be/pages/pattern-en#conjugation - там поддержка Python 3 не заявлена, но портировать конкретно этот модуль должно быть несложно, если он так не заработает.

**Comment by ins2718** [comment]
да, наверно этим и займусь. Правда они там с 2013 его на python 3 портируют, так что, наверно, сложности есть :) .
