### ISSUE TITLE
Изменение параметра score.

### ISSUE THREAD

**Issue by Ulitochka** [kmike/pymorphy2#96]
Добрый день.

Скажите пожалуйста, в результате морфологического анализа есть параметр score:
`morph.parse('стали')
[Parse(word='стали', tag=OpencorporaTag('VERB,perf,intr plur,past,indc'), normal_form='стать', score=0.983766, methods_stack=((<DictionaryAnalyzer>, 'стали', 884, 4),)), ...]
`
как он рассчитывается понятно, но можно ли его корректировать вручную задавая значения?

**Comment by buriy** [comment]
Обрабатывайте результаты вручную после выполнения парсинга и изменяйте, как вам нужно.
```
results = morph.parse(word)
change_score(results)

def change_score(parses):
    for p in parses:
        if p.normal_form=='стать':
           p.score = 0.5
```

**Comment by Ulitochka** [comment]
Предпочел бы использовать сам словарь pymorphy, так как в противному случае мне нужно будет хранить 2-ой словарь для сверки. Например, на основании статистики корпуса у некой формы самым вероятным считается тег А, но мне хочется видеть тег B. Поэтому перед созданием словарей хочется внести коррективы в параметр score.

**Comment by buriy** [comment]
Ну можете исправить код в момент создания словаря, но это будет дольше.
Насколько я понимаю, объекты Parse были сделаны immutable для повышения скорости и защиты от ошибок. 
Я не понимаю, причём тут "хранить 2й словарь для сверки". Для какой сверки?
