### ISSUE TITLE
Значения граммем

### ISSUE THREAD

**Issue by svetlana21** [kmike/pymorphy2#98]
Здравствуйте! 
Я хочу сгенерировать собственные словари из файлов XML в формате OpenCorpora. Скажите, пожалуйста, могу ли я в файлах XML использовать собственные имена граммем  (текст в теге <grammeme><name>...</name>...</grammeme>)? Насколько я понимаю, проблем с этим не должно возникнуть, главное не менять сами теги.

**Comment by kmike** [comment]
Добрый день! Я не совсем понял, что имеется в виду - можно пример, что хочется получить?

Часть названий сейчас зашита в исходном коде (https://github.com/kmike/pymorphy2/blob/afd3a76cd97311bde8c9669ccdd0cef568fb7ae0/pymorphy2/tagset.py#L130), и могут быть некоторые проблемы, если эти стандартные названия не совпадают (хотя вроде все должно работать и с другими названиями, просто некоторые фичи будут недоступны). Это хорошо бы исправить в pymorphy2, но пока руки не дошли.

**Comment by svetlana21** [comment]
Вот тут https://github.com/kmike/pymorphy2/issues/60 вы говорили, что можно создать собственные словари для pymorphy с помощью скриптов вот отсюда: https://github.com/kmike/pymorphy2-dicts. Я хочу создать свои словари для английского. Вот в этом примере https://github.com/kmike/pymorphy2/blob/master/dev_data/toy_dict.xml в списке граммем есть те, которые для английского не актуальны, плюс хочется добавить дополнительные специфические граммемы.
Ну, по крайней мере, генерации словарей наличие/отсутствие каких-то граммем не должно помешать?

**Comment by svetlana21** [comment]
Можно ли не исправлять набор грамматических категорий в исходном коде, а добавить их в xml, но оставить пустыми? Если это не критично для работы pymorphy, то может оказаться выходом из ситуации.

**Comment by svetlana21** [comment]
Продолжаю эксперименты с созданием словарей для английского языка. Проблемы с граммемами удалось решить. Я сгенерировала словарь с помощью https://github.com/kmike/pymorphy2-dicts/blob/master/build-dict.py , добавила английский в pymorphy2.lang. Английский теперь можно указывать в атрибуте lang при создании объекта класса MorphAnalyzer. Однако по словарю слова всё так же не разбираются. Например, если оставить в конфиге DEFAULT_UNITS = [
    [
        units.DictionaryAnalyzer()
        units.LatinAnalyzer()
    ]
],
то при попытке анализа какого-нибудь слова из словаря ему присваивается тег LATN ([Parse(word='abask', tag=OpencorporaTag('LATN'), normal_form='abask', score=0.9, methods_stack=((LatinAnalyzer(score=0.9), 'abask'),))]). Если убрать и units.LatinAnalyzer() из конфига, то выдается вообще пустой список.
Я сравнила свой словарь и словарь pymorphy для РЯ, оказалось, что в моей папке нет файлов paradigm-prefixes.json, prediction-prefixes.dawg, p_t_given_w.intdawg. Чего мне не хватает, чтобы всё заработало? Как формируются и для чего нужны файлы gramtab-opencorpora-ext.json и gramtab-opencorpora-int.json?
