### ISSUE TITLE
Сломанные ссылки на странице документации

### ISSUE THREAD

**Issue by opennota** [kmike/pymorphy2#99]
https://pymorphy2.readthedocs.io/en/latest/internals/dict.html#id12

Ссылки на dawgdic (https://code.google.com/p/dawgdic/) не работают (их две). На github есть зеркала.

**Comment by kmike** [comment]
Привет. Сама ссылка у меня работает, но да, лучше куда-то в другое место ссылаться.

Описания дискового формата dawgdic нет, но он довольно понятный, если почитать код. Есть, например, читалка на питоне - https://github.com/pytries/DAWG-Python/blob/master/dawg_python/wrapper.py

**Comment by opennota** [comment]
Да, работает. Похоже, из-за какого-то расширения у меня вылезало 404.

DAWG-Python уже нашёл, спасибо.
